# Generated by Django 4.2.3 on 2023-07-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='')),
                ('created', models.TimeField(auto_now_add=True)),
                ('update', models.TimeField(auto_now=True)),
            ],
        ),
    ]
